In [2]:
import numpy as np
matrix = np.arange(-4,4,1) #make an array from -4 to 3 by adding 1 
x,y = np.meshgrid(matrix, matrix)

In [3]:
print('Matrix values of y: {}'.format(y))

Matrix values of y: [[-4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3]]


In [4]:
print('Matrix values of y: {}'.format(x))

Matrix values of y: [[-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]
 [-4 -3 -2 -1  0  1  2  3]]


In [5]:
x1 = np.array([1,2,3,4,5])
y1 = np.array([6,7,8,9,10])
cond = [True, False, True, True, False]

#call the value for every array above
z1 = [(x,y,z) for x,y,z in zip(x1,y1,cond)]     #used zip function to illustrated
print(z1)

[(1, 6, True), (2, 7, False), (3, 8, True), (4, 9, True), (5, 10, False)]


In [6]:
np.where(cond, x1, y1)     #if TRUE, call first array x1

array([ 1,  7,  3,  4, 10])

In [7]:
rand = np.random.randn(5,5)

print(rand)

[[-0.01847518 -1.85316327  0.48329978 -0.33297626 -1.08760809]
 [-1.03526911  0.65617447  0.03393195 -0.55410286 -0.35966957]
 [-0.70029033 -0.93348051 -1.05555513 -0.71366543  0.39660984]
 [ 0.39873304 -1.22925914 -0.43855504  0.15085761  0.56255271]
 [-0.76950064  1.91335354  0.43371948  0.39759613  1.15363039]]


In [8]:
#if value in rand > 0, replace it with 1.. else -1

print(np.where(rand>0, 1, -1))

[[-1 -1  1 -1 -1]
 [-1  1  1 -1 -1]
 [-1 -1 -1 -1  1]
 [ 1 -1 -1  1  1]
 [-1  1  1  1  1]]


In [10]:
#to set rand >0 as 1 and <0 with actual values. np.where(condition, nilai positive, nilai negatif)

np.where(rand>0, 1, rand)

array([[-0.01847518, -1.85316327,  1.        , -0.33297626, -1.08760809],
       [-1.03526911,  1.        ,  1.        , -0.55410286, -0.35966957],
       [-0.70029033, -0.93348051, -1.05555513, -0.71366543,  1.        ],
       [ 1.        , -1.22925914, -0.43855504,  1.        ,  1.        ],
       [-0.76950064,  1.        ,  1.        ,  1.        ,  1.        ]])