In [1]:
#to create matrix with i and j with range(n)

from numpy import random
algebra = random.randn(10,5) 

In [4]:
for j in range(10):
    algebra[j] = j
algebra    

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9.]])

In [11]:
#to select any subset of rows
algebra[[2,3,2]]

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [2., 2., 2., 2., 2.]])

In [17]:
#reshape is to reshape the array to new matrix
import numpy as np
new = np.arange(40).reshape(10,4)
print(new)

new[[1,4,3,2],[1,1,3,2]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


array([ 5, 17, 15, 10])

In [18]:
new[[1,4,8,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [19]:
#another way to select particular array using np.ix_function

new[np.ix_([1,4,8,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [16, 19, 17, 18],
       [32, 35, 33, 34],
       [ 8, 11,  9, 10]])

In [20]:
#to transpose the matrix after reshaping 

transpose = np.arange(12).reshape(3,4)
transpose.T      #will change the matrix to (4,3)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [23]:
new = np.arange(40).reshape(10,4)
print(new)
new.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


array([[ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38],
       [ 3,  7, 11, 15, 19, 23, 27, 31, 35, 39]])