In [2]:
#How to create a boolean array?
#Create a 3×3 numpy array of all True’s
import numpy as np
np.full((3,3), True, dtype = bool)
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# How to extract items that satisfy a given condition from 1D array?
#Extract all odd numbers from arr

arr = np.arange(10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

In [15]:
#How to replace items that satisfy a condition with another value in numpy array?
#Extract all multiple of 3 numbers from arr2

arr2 = np.arange(20)
arr2[arr2%3 == 0]

array([ 0,  3,  6,  9, 12, 15, 18])

In [31]:
#Extract all odd numbers from arr
#Replace all odd numbers in arr with -1

arr = np.arange(10)
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
kobe = np.where(arr % 2 == 1, -1, arr)
kobe

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [43]:
#How to reshape an array?
new = np.arange(10)
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
new.reshape(2,-1)   #-1 automatically decide the col for you

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
#How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])      #vstack vertically

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
np.hstack([a, b])       # hstack horizontally

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [62]:
#How to generate custom sequences in numpy without hardcoding in repetition.?
a = np.array([1,2,3])
np.r_[np.repeat(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [64]:
np.r_[np.tile(a,3)]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [65]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [67]:
#How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [68]:
#How to remove from one array those items that exist in another?

np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [75]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [3]:
#How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [12]:
#Q. Convert the function maxx that works on two scalars, to work on two arrays.

def maxx(x,y):
    if x>y:
        return x
    else:
        return y
    


In [13]:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [15]:
pair_max = np.vectorize(maxx, otypes = [float])    
pair_max(a,b)

array([6., 7., 9., 8., 9., 7., 5.])

In [16]:
#How to swap two columns in a 2d numpy array?

arr = np.arange(9).reshape(3,3)
arr

arr[:, [2,0,1]]    #change col


array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [19]:
arr[[1,0,2], :]    #change row

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [22]:
#How to reverse the rows of a 2D array?

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [27]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

new = np.random.uniform(5,10, size =(5,3))
new

array([[9.41795223, 7.53265429, 6.72722167],
       [6.82564028, 6.85067646, 6.32508465],
       [5.94274844, 9.89518543, 6.19178026],
       [5.16259488, 8.33738096, 5.4512288 ],
       [7.87350051, 9.76634323, 5.94776989]])

In [33]:
#Print or show only 3 decimal places of the numpy array rnew

rand = np.random.random([5,3])   #array

np.set_printoptions(precision=3)
rand

array([[0.377, 0.463, 0.863],
       [0.967, 0.425, 0.721],
       [0.178, 0.869, 0.938],
       [0.836, 0.469, 0.462],
       [0.437, 0.645, 0.55 ]])

In [39]:
#How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

np.random.seed(50)
new1 = np.random.random([3,3])/1e3
new1


array([[0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.001],
       [0.   , 0.001, 0.001]])

In [41]:
#How to limit the number of items printed in output of numpy array?

np.set_printoptions(threshold=6)
a = np.arange(20)
a

array([ 0,  1,  2, ..., 17, 18, 19])

In [42]:
# How to print the full numpy array without truncating
np.set_printoptions(threshold=np.nan)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
#How to import a dataset with numbers and texts keeping the text intact in python numpy? TEXT,NUMB IN THE SAME LIST
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)