In [6]:
#import random module from NUmpy
import numpy as np
person = np.array(['Ana', 'Tini', 'Zaza', 'Ana', 'Ana', 'Zaza', 'Aini', 'Zaza', 'Ana', 'Tini', 'Ana'])
print(person == 'Ana')

[ True False False  True  True False False False  True False  True]


In [9]:
#import random no from Numpy

from numpy import random

In [10]:
random_no = random.randn(11,4)

In [11]:
print(random_no)

[[-2.01541074e+00  7.43151095e-01 -5.36672993e-01  1.82266743e-01]
 [ 1.09545753e+00  1.79711321e-01 -1.35164191e+00  2.34689807e-03]
 [ 9.02262668e-01 -4.18916158e-01 -4.08849098e-01  7.90247589e-01]
 [ 1.58303149e-01  9.77852470e-01 -1.35260213e-01 -4.83186341e-01]
 [-1.29262105e-01 -1.11223881e+00  2.42174452e-01 -1.30937794e+00]
 [-7.99985394e-02 -7.08542360e-01 -8.87826228e-01 -2.44550987e+00]
 [-9.84574313e-01  2.12974876e-01  2.66552814e-01 -1.30211517e-01]
 [-2.25244625e-02  1.17738608e-01  1.10159160e+00  1.59069047e+00]
 [-1.13557934e+00  4.10852823e-01  8.44665926e-01  1.36684012e+00]
 [ 4.61837776e-01  7.33359073e-02  7.04858947e-01 -1.78437604e+00]
 [ 1.36557616e+00  1.86601226e+00 -1.00012558e-01  1.46973004e+00]]


In [12]:
#Ana
random_no[person == 'Ana']

array([[-2.01541074,  0.7431511 , -0.53667299,  0.18226674],
       [ 0.15830315,  0.97785247, -0.13526021, -0.48318634],
       [-0.1292621 , -1.11223881,  0.24217445, -1.30937794],
       [-1.13557934,  0.41085282,  0.84466593,  1.36684012],
       [ 1.36557616,  1.86601226, -0.10001256,  1.46973004]])

In [14]:
#not Ana
random_no[~(person == 'Ana')]

array([[ 1.09545753e+00,  1.79711321e-01, -1.35164191e+00,
         2.34689807e-03],
       [ 9.02262668e-01, -4.18916158e-01, -4.08849098e-01,
         7.90247589e-01],
       [-7.99985394e-02, -7.08542360e-01, -8.87826228e-01,
        -2.44550987e+00],
       [-9.84574313e-01,  2.12974876e-01,  2.66552814e-01,
        -1.30211517e-01],
       [-2.25244625e-02,  1.17738608e-01,  1.10159160e+00,
         1.59069047e+00],
       [ 4.61837776e-01,  7.33359073e-02,  7.04858947e-01,
        -1.78437604e+00]])

In [15]:
#using boolen operator &(and) | as or
new_person = (person == 'Ana') | (person == 'Tini') 

In [16]:
print(new_person)

[ True  True False  True  True False False False  True  True  True]


In [17]:
random_no[new_person]

array([[-2.01541074,  0.7431511 , -0.53667299,  0.18226674],
       [ 1.09545753,  0.17971132, -1.35164191,  0.0023469 ],
       [ 0.15830315,  0.97785247, -0.13526021, -0.48318634],
       [-0.1292621 , -1.11223881,  0.24217445, -1.30937794],
       [-1.13557934,  0.41085282,  0.84466593,  1.36684012],
       [ 0.46183778,  0.07333591,  0.70485895, -1.78437604],
       [ 1.36557616,  1.86601226, -0.10001256,  1.46973004]])

In [18]:
#set -ve no to zero value

random_no[random_no <0] = 0
random_no

array([[0.        , 0.7431511 , 0.        , 0.18226674],
       [1.09545753, 0.17971132, 0.        , 0.0023469 ],
       [0.90226267, 0.        , 0.        , 0.79024759],
       [0.15830315, 0.97785247, 0.        , 0.        ],
       [0.        , 0.        , 0.24217445, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.21297488, 0.26655281, 0.        ],
       [0.        , 0.11773861, 1.1015916 , 1.59069047],
       [0.        , 0.41085282, 0.84466593, 1.36684012],
       [0.46183778, 0.07333591, 0.70485895, 0.        ],
       [1.36557616, 1.86601226, 0.        , 1.46973004]])