In [2]:
import numpy as np

In [4]:
new = np.random.randn(8)   #also can use (i,j) matrix
print(new)

[ 1.03073682 -0.42622435 -0.3417883   0.0689872   0.71852861 -0.01398739
  0.93628366 -1.41408324]


In [5]:
new.sort()
new

array([-1.41408324, -0.42622435, -0.3417883 , -0.01398739,  0.0689872 ,
        0.71852861,  0.93628366,  1.03073682])

In [8]:
new.sort(0)

array([-1.41408324, -0.42622435, -0.3417883 , -0.01398739,  0.0689872 ,
        0.71852861,  0.93628366,  1.03073682])

In [9]:
new2 = np.random.randn(4,4)
new2

array([[ 1.17978959, -0.17699003, -0.41806006, -1.64542653],
       [-0.51384063,  1.23420732,  1.06761352, -0.93810882],
       [ 0.23733154, -0.38574773,  1.36448378, -0.69268901],
       [ 0.30541022, -0.10053523, -0.77514337, -1.10138765]])

In [13]:
new2.sort(1)   #sorted by row
new2

array([[-1.64542653, -0.41806006, -0.17699003,  1.17978959],
       [-0.93810882, -0.51384063,  1.06761352,  1.23420732],
       [-0.69268901, -0.38574773,  0.23733154,  1.36448378],
       [-1.10138765, -0.77514337, -0.10053523,  0.30541022]])

In [15]:
personals = np.array(['Kobe', 'Nopal', 'Cutegirl', 'Bonda', 'Kobe', 'Manu', 'Kobe'])

In [16]:
np.unique(personals)       #show array of DISTINCT personal

array(['Bonda', 'Cutegirl', 'Kobe', 'Manu', 'Nopal'], dtype='<U8')

In [18]:
set(personals)

{'Bonda', 'Cutegirl', 'Kobe', 'Manu', 'Nopal'}

In [22]:
np.in1d(personals, ['Kobe'])    #boolean to check something

array([ True, False, False, False,  True, False,  True])

In [28]:
np.intersect1d(personals, 'Kobe')

array(['Kobe'], dtype='<U8')

In [33]:
np.union1d(personals, 'Kobe')              

array(['Bonda', 'Cutegirl', 'Kobe', 'Manu', 'Nopal'], dtype='<U8')

In [35]:
cp = np.array([[1,2,3],[4,5,6]])

In [41]:
dp = np.array([[7,8],[9,10],[11,12]])

print('CP array :{}'.format(cp))
cp.dot(dp)                           #eelement wise multipication


CP array :[[1 2 3]
 [4 5 6]]


array([[ 58,  64],
       [139, 154]])

In [52]:
np.delete(dp, 1)

array([ 7,  9, 10, 11, 12])

In [83]:
#numpy.linalg has std matrix operations like determinants and inverse
from numpy.linalg import inv,qr
sp = np.random.randn(5,5)
print(sp)
print(inv(sp))
rt = inv(sp)

[[-1.98721567  0.03836335  0.06309125  0.46203718  0.93973783]
 [ 0.84225352  0.45605925  1.2223877   1.49918428 -1.56567048]
 [ 0.24876604 -0.53390642  0.21612774  0.91876847 -1.65878476]
 [-0.57658378  0.66589483  1.78991624 -0.11899816 -0.89860615]
 [ 0.16159665  0.3471577   0.69002287  0.10632703  0.51854422]]
[[-0.37724486  0.01199053  0.07499687 -0.22418141  0.57128659]
 [ 0.09963732  1.3190661  -1.93635331  0.15085275 -2.13066932]
 [-0.08746564 -0.56937837  0.8285931   0.25801077  1.53707921]
 [ 0.35219069  0.48461121  0.04056168 -0.42942878  0.21053231]
 [ 0.09503055 -0.22853356  0.16206858 -0.28640986  1.08834533]]


In [65]:
# to calculate product of matrix and its inverse
sp.dot(rt)

array([[ 1.00000000e+00,  4.30211422e-16,  1.07552856e-16,
        -5.52943108e-17,  6.41847686e-17],
       [ 1.11022302e-16,  1.00000000e+00,  1.94289029e-16,
         3.12250226e-17,  2.77555756e-17],
       [ 1.80411242e-16,  4.02455846e-16,  1.00000000e+00,
        -1.30104261e-18,  0.00000000e+00],
       [-4.44089210e-16,  6.66133815e-16,  5.55111512e-17,
         1.00000000e+00, -1.11022302e-16],
       [-1.38777878e-16,  9.71445147e-17,  3.46944695e-18,
         7.80625564e-18,  1.00000000e+00]])

In [66]:
#other matrix function:
#diag(return diagonal)
#trace(sum of diagonal elements)
#det(matrix determinant)

In [85]:
zp = np.random.randn(3,3)
zp

array([[ 0.47271471,  0.25658588,  0.27397458],
       [ 1.39066957, -1.02059787, -0.12917927],
       [-0.10456499,  0.44357564,  0.11051933]])

In [93]:
mm = np.mat("3 4;5 6")
mm

matrix([[3, 4],
        [5, 6]])

In [94]:
np.linalg.det(mm)

-2.0000000000000013