In [4]:
import numpy as np
rdm = np.random.randn(4,4)
rdm

array([[ 1.60101353,  1.87207381, -1.3356139 , -0.34169591],
       [ 1.38231591,  0.54039347,  0.92095162, -0.41623328],
       [-2.46150636, -0.62903515,  0.38586352,  1.15589632],
       [ 0.12065424,  0.49017015, -1.12613408,  0.17430961]])

In [7]:
print(rdm.mean())
#or
print(np.mean(rdm))

0.14583896867559523
0.14583896867559523


In [10]:
print(rdm.sum())

2.3334234988095237


In [13]:
jp = np.arange(12).reshape(4,3)
print("The arrays are: {}".format(jp))

The arrays are: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
print("THe sum of rows are :{}".format(np.sum(jp, axis =0)))

THe sum of rows are :[18 22 26]


In [21]:
print(jp.sum(1))

[ 3 12 21 30]


In [26]:
print(jp.cumsum(1))

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]


In [30]:
xp = np.random.randn(100)
print((xp>0).sum())
print((xp<0).sum())    #also can use std,var,min,max, argmin,argmax

46
54


In [32]:
randf = np.array([True,False,True,False,True,False])

In [35]:
print(randf.any())   #to check if any value are true
print(randf.all())    #return False if a value is false, also work for non-boolean arrays

True
False
